services: 
  postgres_imdb:
    container_name: IMDB_Pg
    image: postgres:16
    restart: always
    environment: 
      POSTGRES_PASSWORD: admin 
      POSTGRES_USER: admin
      POSTGRES_DB: imdb
    ports:
      - 5433:5432
    volumes:
      - pg_imdb_data:/var/lib/postgresql/data
      - ./init-imdb:/docker-entrypoint-initdb.d

  postgres_cinecheck:
    container_name: CineCheck_Pg
    image: postgres:16
    restart: always
    environment: 
      POSTGRES_PASSWORD: admin 
      POSTGRES_USER: admin
      POSTGRES_DB: cinecheck
    ports:
      - 5432:5432
    volumes:
      - pg_cinecheck_data:/var/lib/postgresql/data
      - ./init-app:/docker-entrypoint-initdb.d

volumes:
  pg_cinecheck_data:
  pg_imdb_data: